### PR TITLE
merge updates from main plugin

### PR DESCRIPTION
**Pull request by athe0i**

### CODE REVIEW

**Comment by dwahlqvist** [comment]
Waiting for feedback

**Comment by ptraing** [comment]
Hi @dwahlqvist ,
It is good for us.

**Comment by ptraing** [comment]
Hi @dwahlqvist , 
finally we saw a worry. in the di.xml it is necessary to remove the declaration of the plugin.

Remove : 
` <type name="Magento\Customer\Model\AccountManagement">
        <plugin disabled="false" name="Rule_RuleMailer_Plugin_Magento_Customer_Model_AccountManagement" sortOrder="10" type="Rule\RuleMailer\Plugin\Magento\Customer\Model\AccountManagement"/>
    </type>`

**Comment by dwahlqvist** [comment]
@athe0i can you (or Igor maybe?) update according to their feedback and then merge this?

**Comment by dwahlqvist** [comment]
@ptraing fixed and merged now 😄

**Pull request merged**
